name: CI
run-name: ${{ github.actor }} run CI
env:
  CC: gcc
  CXX: g++
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install gcc g++ make cmake
      - run: mkdir -p build && cd build && cmake .. && make
      - run: cd ..
